### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant parsing Yoast SEO

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-shortcodes#65]
Processing: log,Middleware::log,vendor_prefixed/guzzlehttp/guzzle/src/Middleware.php
```
Fatal error: Uncaught Error: Undefined constant 'YoastSEO_Vendor\Psr\Log\LogLevel__INFO' in /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php:29
Stack trace:
#0 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(29): ReflectionParameter->getDefaultValue()
#1 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(104): oikai_print_param_info(Object(ReflectionParameter), 'string', '$logLevel', 'Level at which ...')
#2 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(1131): oikai_print_param(Object(ReflectionParameter), Object(DocBlock))
#3 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(2577): oikai_reflect_parameters(Object(oiksc_token_object), Object(DocBlock))
#4 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-apis.php(536): oikai_build_apiref('Middleware::log', 'vendor_prefixed...', 'wordpress-s in /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php on line 29
```

**Comment by bobbingwide** [comment]
Time to fix this problem!

### Problem explanations 
The line that caused the problem was:
```
 public static function log(\YoastSEO_Vendor\Psr\Log\LoggerInterface $logger, 
\YoastSEO_Vendor\GuzzleHttp\MessageFormatter $formatter, 
$logLevel = \YoastSEO_Vendor\Psr\Log\LogLevel::INFO)
```
The code fails when trying to use ReflectionParameter method to get the default value.
We've checked that a value is available, but also need to check to see if this is a constant.

which for the third parameter is a constant.
