### ISSUE TITLE
Cannot skip a file that fails to parse

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-shortcodes#74]
When attempting to skip a file that contained a function that failed to parse we get a fatal error.
```
Fatal error: Uncaught Error: Call to undefined function oikai_get_oik_api_byname() in /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php:337
Stack trace:
#0 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php(312): _ca_does_api_need_processing(Object(oiksc_token_object), 'tests/ajax.php', 'plugin', 'easy-digital-do...')
#1 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php(248): _ca_doapis_local('tests/ajax.php', 'easy-digital-do...', 'plugin')
#2 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-apis.php(843): _ca_dofile_local('tests/ajax.php', 'easy-digital-do...', 'plugin')
#3 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php(205): oiksc_do_files(Array, 'easy-digital-do...', 'plugin', '_ca_dofile_loca...', 446)
#4 /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php(76): _ca_doaplugin_local('easy-digital-do...', '0', 446)
#5 /hom in /home/bworguk/public_html/wp-content/plugins/oik-shortcodes/admin/oik-create-apis.php on line 337
```

Parsing of EDD and Jetpack with WordPress 5.3 is incomplete because of this.

**Comment by bobbingwide** [comment]
We also need to be able to restart processing from a particular file ($start) when the $previous SHA is specified as 0. 
And when we are restarting we need to update the parse status for the component
