### ISSUE TITLE
Uncaught Error: Call to undefined function ep()

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-shortcodes#95]
```
21-Nov-2024 18:06:33 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ep() in /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php:596
Stack trace:
#0 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(2681): oikai_reflect_descriptions(Object(DocBlock))
#1 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php(2817): oikai_build_apiref('oiksc_get_sourc...', 'admin/oik-short...', 'oik-shortcodes', NULL, 26257, true, '5025')
#2 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik/libs/oik-shortcodes.php(229): oikai_apiref(Array, '', 'bw_api')
#3 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/shortcodes.php(434): bw_shortcode_event(Array, '', 'bw_api')
#4 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(118): do_shortcode_tag(Array)
#5 [internal function]: do_shortcode_tag_earlier(Array)
#6 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(95): preg_replace_callback('/\\[(\\[?)(bw_api...', 'do_shortcode_ta...', '<span id="more-...')
#7 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): do_shortcode_earlier('<span id="more-...')
#8 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('<span id="more-...', Array)
#9 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/post-template.php(256): apply_filters('the_content', '<span id="more-...')
#10 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/post.php(486): the_content()
#11 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): genesis_do_post_content('')
#12 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#13 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#14 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(119): do_action('genesis_entry_c...')
#15 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(38): genesis_standard_loop()
#16 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): genesis_do_loop('')
#17 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#18 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#19 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/framework.php(66): do_action('genesis_loop')
#20 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/single.php(15): genesis()
#21 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/template-loader.php(106): include('/home/customer/...')
#22 /home/customer/www/oik-plugins.co.uk/public_html/wp-blog-header.php(19): require_once('/home/customer/...')
#23 /home/customer/www/oik-plugins.co.uk/public_html/index.php(17): require('/home/customer/...')
#24 {main}
  thrown in /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-shortcodes/shortcodes/oik-api-importer.php on line 596
[
```

**Comment by bobbingwide** [comment]
Delivered in v1.41.4/5
